apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  annotations:
    argocd-autopilot.argoproj-labs.io/default-dest-server: https://kubernetes.default.svc
    argocd.argoproj.io/sync-options: PruneLast=true
    argocd.argoproj.io/sync-wave: "-2"
  name: airflow
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  description: airflow project
  destinations:
  - namespace: '*'
    server: '*'
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
  sourceRepos:
  - '*'
status: {}

---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  name: airflow
  namespace: argocd
spec:
  generators:
  # - git:
  #     files:
  #     - path: apps/**/airflow/config.json
  #     repoURL: https://github.com/sudeepgupta90/playwithargo.git
  #     requeueAfterSeconds: 20
  #     revision: ""
  #     template:
  #       metadata: {}
  #       spec:
  #         destination: {}
  #         project: ""
  #         source:
  #           repoURL: ""
  # - git:
  #     files:
  #     - path: apps/**/airflow/config_dir.json
  #     repoURL: https://github.com/sudeepgupta90/playwithargo.git
  #     requeueAfterSeconds: 20
  #     revision: ""
  #     template:
  #       metadata: {}
  #       spec:
  #         destination: {}
  #         project: ""
  #         source:
  #           directory:
  #             exclude: '{{ exclude }}'
  #             include: '{{ include }}'
  #             jsonnet: {}
  #             recurse: true
  #           repoURL: ""
  - list:
      elements:
        - namespace: data-mlp-airflow
        - namespace: data-ods-airflow
  template:
    metadata:
      labels:
        app.kubernetes.io/managed-by: argocd-autopilot
        app.kubernetes.io/name: '{{ appName }}'
      name: '{{namespace}}'
      namespace: argocd
    spec:
      destination:
        namespace: '{{namespace}}'
      ignoreDifferences:
      - group: argoproj.io
        jsonPointers:
        - /status
        kind: Application
      project: airflow
      source:
        path: helm-charts/airflow/
        repoURL: https://github.com/sudeepgupta90/playwithargo.git
        targetRevision: HEAD
      syncPolicy:
        automated:
          allowEmpty: true
          prune: true
          selfHeal: true
  syncPolicy: {}
status: {}
